openapi: 3.0.3
info:
  title: Account API
  description: API for managing accounts
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/v1/accounts:
    get:
      tags:
        - Accounts
      summary: Get all accounts
      operationId: getAllAccounts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponse'
    post:
      tags:
        - Accounts
      summary: Create a new account
      operationId: save
      requestBody:
        description: Account object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '200':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '409':
          description: Conflict - Customer does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/accounts/{id}:
    get:
      tags:
        - Accounts
      summary: Find account by ID
      operationId: getByAccountId
      parameters:
        - name: id
          in: path
          description: ID of account to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Accounts
      summary: Update an existing account
      operationId: update
      parameters:
        - name: id
          in: path
          description: ID of account to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Account object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '200':
          description: Account updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Accounts
      summary: Delete account by ID
      operationId: delete
      parameters:
        - name: id
          in: path
          description: ID of account to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Account deleted successfully
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - Account has transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/accounts/customer/{id}:
    get:
      tags:
        - Accounts
      summary: Find accounts by customer ID
      operationId: getByCustomerId
      parameters:
        - name: id
          in: path
          description: ID of customer to find accounts for
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResponse'
        '404':
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
    AccountRequest:
      type: object
      required:
        - accountNumber
        - accountType
        - initialBalance
        - status
        - customerId
      properties:
        accountNumber:
          type: string
          minLength: 6
          maxLength: 10
        accountType:
          type: string
          enum:
            - CHECKING
            - SAVINGS
        initialBalance:
          type: number
          format: decimal
          minimum: 0
          exclusiveMinimum: true
        status:
          type: boolean
        customerId:
          type: integer
          format: int64
    AccountResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        accountNumber:
          type: string
        accountType:
          type: string
        initialBalance:
          type: number
          format: decimal
        status:
          type: boolean
        customerName:
          type: string
    CustomerSnapshotResponse:
      type: object
      properties:
        customerId:
          type: integer
          format: int64
        customerName:
          type: string
