openapi: 3.0.3
info:
  title: Transaction API
  description: API for managing movements
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /api/v1/movements:
    get:
      tags:
        - Movements
      summary: Get all movements
      operationId: getAllMovements
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementResponse'
    post:
      tags:
        - Movements
      summary: Create a new movement
      operationId: save
      requestBody:
        description: Movement object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementRequest'
      responses:
        '200':
          description: Movement created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponse'
        '409':
          description: Conflict - Account does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/movements/{id}:
    get:
      tags:
        - Movements
      summary: Find movement by ID
      operationId: findById
      parameters:
        - name: id
          in: path
          description: ID of movement to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponse'
        '404':
          description: Movement not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Movements
      summary: Update an existing movement
      operationId: update
      parameters:
        - name: id
          in: path
          description: ID of movement to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Movement object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovementRequest'
      responses:
        '200':
          description: Movement updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovementResponse'
        '404':
          description: Movement not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Movements
      summary: Delete movement by ID
      operationId: delete
      parameters:
        - name: id
          in: path
          description: ID of movement to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Movement deleted successfully
        '404':
          description: Movement not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/movements/account/{id}:
    get:
      tags:
        - Movements
      summary: Find movements by account ID
      operationId: getByAccountId
      parameters:
        - name: id
          in: path
          description: ID of account to find movements for
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementResponse'

  /api/v1/movements/reports:
    get:
      tags:
        - Movements
      summary: Get movements report by date range and customer
      operationId: getAllMovementsByDateRanges
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: customerId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovementResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string
    MovementRequest:
      type: object
      required:
        - type
        - value
        - balance
        - accountId
      properties:
        date:
          type: string
          format: date
        type:
          type: string
          enum:
            - DEPOSIT
            - WITHDRAWAL
        value:
          type: number
          format: double
        balance:
          type: number
          format: decimal
          minimum: 0
          exclusiveMinimum: true
        accountId:
          type: integer
          format: int64
          minimum: 0
          exclusiveMinimum: true
    MovementResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
          format: date
        type:
          type: string
        value:
          type: number
          format: double
        balance:
          type: number
          format: decimal
        customer:
          type: string
        accountNumber:
          type: string
        initialBalance:
          type: number
          format: decimal
        status:
          type: boolean
